import './globals.css'
import React, { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from './components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home | Milestones',
  description: 'Generated by create next app',
}

type TProps = {
  children: ReactNode
}

const RootLayout: FC<TProps> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}

export default RootLayout
