import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React, { FC, ReactNode } from 'react'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type TProps = {
  children: ReactNode
}

const RootLayout: FC<TProps> = ({ children }) => {
  return (
    <html lang='en'>
      {/* <body className={inter.className}>{children}</body> */}
      <body className=''>{children}</body>
    </html>
  )
}

export default RootLayout
