import { Metadata } from 'next'
import React, { FC, ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'About | Milestones',
  description: 'Generated by create next app',
}

type TProps = {
  children: ReactNode
}

const StandardLayout: FC<TProps> = ({ children }) => {
  return <div>{children}</div>
}

export default StandardLayout
